ARG NODE_VERSION=22.13.1
ARG PNPM_VERSION=10.0.0

FROM node:${NODE_VERSION}-alpine AS base

WORKDIR /usr/src/app

RUN --mount=type=cache,target=/root/.npm \
  npm install -g pnpm@${PNPM_VERSION}

FROM base

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma/
# Run migrations
CMD ["pnpm", "prisma:migrate:deploy"]

